use_frameworks!

abstract_target 'StarsKitAbstract' do
  platform :ios, '9.0'
  
  pod 'StarsKit', :path => '../'
  pod 'SwiftLint'
  
  target 'StarsKit_Example' do
  end
  
  target 'StarsKit_ExampleTests' do
    pod 'SwiftDate', '~> 4.5.1'
  end
  
  target 'StarsKit_ExampleUITests' do
  end
  
end


